print('#'*75)
print('Welcome to Python Patterns...')
print('You can print any pattern, just call the corresponding function')
print('Functions: square(), right_angled_triangle(), pyramid(), hollow_diamond()')
print('#'*75)